const $=s=>document.querySelector(s);
const AR=["فهم الذكاء الاصطناعي","البداية الصحيحة مع أدوات الذكاء الاصطناعي","هندسة الأوامر: كيف تتحدث مع AI","الذكاء الاصطناعي للتعلم","الذكاء الاصطناعي للعمل","الذكاء الاصطناعي للأعمال","إنشاء المحتوى باستخدام AI","التحقق والخصوصية والأمان","سير العمل المتقدم","خطة تطبيق لمدة 30 يومًا"];
const EN=["Understanding Artificial Intelligence","Getting Started with AI Tools","Prompt Engineering: How to Talk to AI","AI for Learning","AI for Work","AI for Business","Creating Content with AI","Verification, Privacy & Safety","Advanced AI Workflows","Your 30-Day AI Action Plan"];
let project=null;
function starter(lang,i){return lang==="ar"?`افتتاحية الفصل:\nابدأ بسؤال أو مشكلة حقيقية يواجهها القارئ.\n\nالمحتوى الرئيسي:\n1. الفكرة الأساسية الأولى + مثال عملي.\n2. الفكرة الأساسية الثانية + مثال عملي.\n3. الفكرة الأساسية الثالثة + مثال عملي.\n\nطبّق الآن:\nاكتب تمرينًا صغيرًا يستطيع القارئ تنفيذه فورًا.\n\nالخلاصة:\n• الفكرة الأولى\n• الفكرة الثانية\n• الفكرة الثالثة`:`Chapter Hook:\nOpen with a real question or problem the reader faces.\n\nMain Content:\n1. Key idea + practical example.\n2. Key idea + practical example.\n3. Key idea + practical example.\n\nAction Step:\nAdd one task the reader can do immediately.\n\nKey Takeaways:\n• Takeaway one\n• Takeaway two\n• Takeaway three`;}
function render(p){project=p;$("#welcome").hidden=true;$("#editor").hidden=false;$("#title").textContent=p.topic;let titles=p.lang==="ar"?AR:EN;
$("#editor").innerHTML=`<div class="tools"><button onclick="copyAll()">نسخ الكل</button><button onclick="downloadTxt()">تنزيل TXT</button><button onclick="window.print()">طباعة / PDF</button><button onclick="resetBook()">مشروع جديد</button></div>`+
titles.map((t,i)=>`<details class="chapter" ${i===0?"open":""}><summary>${String(i+1).padStart(2,"0")} — ${t}</summary><div class="body"><textarea data-i="${i}" placeholder="اكتب محتوى الفصل هنا...">${p.chapters?.[i]||starter(p.lang,i)}</textarea></div></details>`).join("")+
`<div class="extras"><h2>${p.lang==="ar"?"مواد الكتاب الإضافية":"Book Extras"}</h2><details class="chapter"><summary>Checklist / Templates / Resources</summary><div class="body"><textarea id="extras">${p.extras||""}</textarea></div></details><details class="chapter"><summary>Copyright & Disclaimer</summary><div class="body"><textarea id="legal">${p.legal||legalText(p)}</textarea></div></details><details class="chapter"><summary>Sales Assets</summary><div class="body"><textarea id="sales">${p.sales||salesText(p)}</textarea></div></details></div>`;
bindAuto(); updateProgress();}
function legalText(p){return p.lang==="ar"?`© 2026 ${p.author||"MUHAMMED DIJITAL"}. جميع الحقوق محفوظة.\n\nهذا الكتاب لأغراض تعليمية عامة. يجب التحقق من المعلومات المهمة والمصادر الحديثة قبل اتخاذ قرارات مهنية أو مالية أو قانونية أو صحية.`:`© 2026 ${p.author||"MUHAMMED DIJITAL"}. All rights reserved.\n\nThis book is for general educational purposes. Verify important information and current sources before making professional, financial, legal, or health decisions.`}
function salesText(p){return `TITLE OPTIONS:\n1. ${p.topic}\n2. ${p.topic}: A Practical Guide\n3. ${p.topic}: From Beginner to Practical Use\n\nDESCRIPTION:\n[Write a clear 150-word benefit-focused sales description here.]\n\n7 KEYWORDS:\n[Add seven accurate search phrases relevant to the finished book.]\n\nCOVER PROMPTS:\n1. Minimal premium nonfiction cover...\n2. Modern technology editorial cover...\n3. Bold typography professional cover...`}
$("#create").onclick=()=>{let topic=$("#topic").value.trim();if(!topic){$("#topic").focus();return}render({topic,lang:$("#bookLang").value,aud:$("#aud").value,goal:$("#goal").value,author:$("#author").value||"MUHAMMED DIJITAL",chapters:[]});save()};
function collect(){if(!project)return null;project.chapters=[...document.querySelectorAll("textarea[data-i]")].map(x=>x.value);project.extras=$("#extras")?.value||"";project.legal=$("#legal")?.value||"";project.sales=$("#sales")?.value||"";return project}
function save(){let p=collect()||project;if(p)localStorage.setItem("muhammed_dijital_bookforge_v2",JSON.stringify(p))}
$("#save").onclick=()=>{save();alert("تم حفظ المشروع على هذا الجهاز ✓")};$("#load").onclick=()=>{let p=localStorage.getItem("muhammed_dijital_bookforge_v2");if(p)render(JSON.parse(p));else alert("لا يوجد مشروع محفوظ بعد.")};
function bindAuto(){document.querySelectorAll("#editor textarea").forEach(x=>x.addEventListener("input",()=>{save();updateProgress()}))}
function updateProgress(){let xs=[...document.querySelectorAll("textarea[data-i]")];let n=xs.filter(x=>x.value.trim().length>200).length;$("#progress").textContent=n+"/10"}
function allText(){let p=collect(),out=p.topic+"\nBy "+p.author+"\n\n";document.querySelectorAll(".chapter").forEach(c=>{out+=c.querySelector("summary").textContent+"\n"+c.querySelector("textarea").value+"\n\n"});return out}
function copyAll(){navigator.clipboard.writeText(allText()).then(()=>alert("تم النسخ ✓"))}
function downloadTxt(){let b=new Blob([allText()],{type:"text/plain;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=(project.topic||"book")+".txt";a.click();URL.revokeObjectURL(a.href)}
function resetBook(){if(confirm("بدء مشروع جديد؟ تأكد من حفظ مشروعك أولاً.")){project=null;$("#editor").hidden=true;$("#welcome").hidden=false;$("#title").textContent="مشروع جديد";$("#progress").textContent="0/10"}}
$("#themeBtn").onclick=()=>document.body.classList.toggle("light");
$("#langBtn").onclick=()=>{let ar=document.documentElement.dir==="rtl";document.documentElement.dir=ar?"ltr":"rtl";$("#langBtn").textContent=ar?"AR":"EN"};
window.addEventListener("beforeunload",save);