const $=s=>document.querySelector(s);
const TITLES={
ar:["مقدمة عملية إلى الموضوع","المفاهيم والأساسيات","البداية الصحيحة خطوة بخطوة","الأدوات والأساليب الأساسية","التطبيق في التعلم والحياة","التطبيق في العمل","التطبيق في الأعمال والمشاريع","الأخطاء والمخاطر وكيف تتجنبها","سير عمل متقدم وفعّال","خطة تطبيق لمدة 30 يومًا"],
en:["A Practical Introduction","Core Concepts and Foundations","Getting Started Step by Step","Essential Tools and Methods","Applying It to Learning and Life","Applying It at Work","Applying It in Business","Mistakes, Risks and How to Avoid Them","Advanced and Efficient Workflows","Your 30-Day Action Plan"],
de:["Praktische Einführung","Grundbegriffe und Grundlagen","Der richtige Einstieg Schritt für Schritt","Wichtige Werkzeuge und Methoden","Anwendung beim Lernen und im Alltag","Anwendung bei der Arbeit","Anwendung im Business","Fehler, Risiken und wie man sie vermeidet","Fortgeschrittene Workflows","Dein 30-Tage-Aktionsplan"]};
let project=null,timer=null;const KEY="muhammed_dijital_bookforge_v3";
const esc=s=>(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const wc=s=>(s||"").trim()?s.trim().split(/\s+/).length:0;
function titles(topic,lang){
 if(lang==="ar"&&/ذكاء|AI|اصطناعي/i.test(topic))return["فهم الذكاء الاصطناعي","البداية الصحيحة مع أدوات الذكاء الاصطناعي","هندسة الأوامر: كيف تتحدث مع AI","الذكاء الاصطناعي للتعلم","الذكاء الاصطناعي للعمل","الذكاء الاصطناعي للأعمال","إنشاء المحتوى باستخدام AI","التحقق والخصوصية والأمان","سير العمل المتقدم","خطة تطبيق لمدة 30 يومًا"];
 if(lang==="en"&&/\bAI\b|artificial intelligence/i.test(topic))return["Understanding Artificial Intelligence","Getting Started with AI Tools","Prompt Engineering: How to Talk to AI","AI for Learning","AI for Work","AI for Business","Creating Content with AI","Verification, Privacy & Safety","Advanced AI Workflows","Your 30-Day AI Action Plan"];
 let a=[...TITLES[lang]];a[0]+=": "+topic;return a;
}
function starter(lang,t){if(lang==="ar")return`افتتاحية الفصل:\nابدأ بمشكلة أو سؤال حقيقي مرتبط بـ "${t}".\n\nالمحتوى الرئيسي:\n1. الفكرة الأولى + مثال عملي.\n2. خطوات واضحة قابلة للتطبيق.\n3. حالة تطبيقية أو مثال واقعي.\n4. الأخطاء الشائعة وكيفية تجنبها.\n\nطبّق الآن:\nأضف تمرينًا يستطيع القارئ تنفيذه فورًا.\n\nالخلاصة:\n• أهم فكرة\n• أهم تطبيق\n• الخطوة التالية`;
if(lang==="de")return`Einstieg:\nBeginne mit einem echten Problem zu „${t}“.\n\nHauptinhalt:\n1. Kernidee mit praktischem Beispiel.\n2. Klare Schritte.\n3. Realistischer Anwendungsfall.\n4. Typische Fehler vermeiden.\n\nHandlungsaufforderung:\nEine sofort umsetzbare Aufgabe.\n\nZusammenfassung:\n• Kerngedanke\n• Anwendung\n• Nächster Schritt`;
return`Chapter Hook:\nOpen with a real problem related to "${t}".\n\nMain Content:\n1. Key idea + practical example.\n2. Clear actionable steps.\n3. A realistic use case.\n4. Common mistakes and how to avoid them.\n\nAction Step:\nAdd one task the reader can do immediately.\n\nKey Takeaways:\n• Core idea\n• Practical application\n• Next step`}
function promptFor(i){let p=collect(),lang=p.lang==="ar"?"العربية الفصحى المبسطة":p.lang==="de"?"native Hochdeutsch":"native English";return`أنت محرر كتب إلكترونية محترف. اكتب الفصل ${i+1} من كتاب "${p.topic}".\nعنوان الفصل: "${p.titles[i]}".\nالجمهور: ${p.aud}. الهدف: ${p.goal}.\nاللغة: ${lang}. الطول: 1200–1800 كلمة.\nاستخدم Hook قوي، 3–5 نقاط، أمثلة واقعية، خطوات عملية، Action Step، ثم 3 خلاصات. تجنب الحشو والتكرار والادعاءات غير الموثقة. أخرج نص الفصل فقط.`}
function legal(p){return`© 2026 ${p.author}. All rights reserved.\n\nهذا الكتاب لأغراض تعليمية عامة. تحقّق من المعلومات المهمة والمصادر الحديثة قبل اتخاذ قرارات مهنية أو مالية أو قانونية أو صحية.`}
function sales(p){return`SEO TITLE OPTIONS\n1. ${p.topic}\n2. ${p.topic}: A Practical Guide\n3. ${p.topic}: From Beginner to Practical Use\n\nSUBTITLE\n[Benefit-driven subtitle]\n\n150-WORD SALES DESCRIPTION\n[Problem → promise → benefits → call to action]\n\n7 KEYWORDS\n1. [keyword]\n2. [keyword]\n3. [keyword]\n4. [keyword]\n5. [keyword]\n6. [keyword]\n7. [keyword]\n\n3 COVER PROMPTS\n1. Premium minimalist nonfiction cover for: ${p.topic}\n2. Modern editorial cover, strong typography, for: ${p.topic}\n3. Bold commercial ebook cover for: ${p.topic}`}
function extras(){return`STARTER CHECKLIST\n☐ حدد مشكلة القارئ الأساسية\n☐ تحقق من الحقائق المهمة\n☐ اجعل كل فصل عمليًا وغير مكرر\n☐ أضف Action Step لكل فصل\n☐ راجع النص النهائي\n☐ راجع العنوان والوصف والكلمات المفتاحية\n\nWORKSHEET\nهدف القارئ:\nالمشكلة الحالية:\nالنتيجة المطلوبة:\nأول خطوة:\n\n30-DAY PLAN\nWeek 1: Outline & research\nWeek 2: Chapters 1–5\nWeek 3: Chapters 6–10\nWeek 4: Edit, format & publish`}
function render(p){project=p;$("#welcome").hidden=true;$("#editor").hidden=false;$("#title").textContent=p.topic;p.titles=p.titles?.length===10?p.titles:titles(p.topic,p.lang);
$("#editor").innerHTML=`<div class="tools"><button onclick="copyAll()">نسخ الكل</button><button onclick="downloadTxt()">TXT</button><button onclick="downloadMd()">Markdown</button><button onclick="window.print()">PDF / طباعة</button><button onclick="resetBook()">مشروع جديد</button></div>`+
p.titles.map((t,i)=>`<details class="chapter" ${i===0?"open":""}><summary>${String(i+1).padStart(2,"0")} — ${esc(t)}</summary><div class="body"><div class="wordrow"><span id="w${i}" class="wordbadge">0 كلمة</span><button class="mini" onclick="togglePrompt(${i})">✦ Prompt Studio</button></div><div id="p${i}" class="promptbox"><b>AI Writing Prompt</b><pre>${esc(promptFor(i))}</pre><button class="mini" onclick="copyPrompt(${i})">نسخ Prompt</button></div><textarea data-i="${i}">${esc(p.chapters?.[i]||starter(p.lang,t))}</textarea></div></details>`).join("")+
`<div class="extras"><h2>مواد الكتاب الإضافية</h2><details class="chapter"><summary>Checklist / Worksheets / 30-Day Plan</summary><div class="body"><textarea id="extras">${esc(p.extras||extras())}</textarea></div></details><details class="chapter"><summary>Copyright & Disclaimer</summary><div class="body"><textarea id="legal">${esc(p.legal||legal(p))}</textarea></div></details><details class="chapter"><summary>KDP / Gumroad / Etsy Sales Kit</summary><div class="body"><textarea id="sales">${esc(p.sales||sales(p))}</textarea></div></details></div>`;
document.querySelectorAll("#editor textarea").forEach(x=>x.addEventListener("input",()=>{clearTimeout(timer);timer=setTimeout(save,300);progress()}));progress();save()}
function collect(){if(!project)return null;project.chapters=[...document.querySelectorAll("textarea[data-i]")].map(x=>x.value);project.extras=$("#extras")?.value||"";project.legal=$("#legal")?.value||"";project.sales=$("#sales")?.value||"";return project}
function save(){let p=collect()||project;if(p)localStorage.setItem(KEY,JSON.stringify(p))}
function progress(){let xs=[...document.querySelectorAll("textarea[data-i]")],done=0,total=0;xs.forEach((x,i)=>{let n=wc(x.value);total+=n;if(n>=1200)done++;let b=$("#w"+i);if(b){b.textContent=n+" كلمة • "+Math.min(100,Math.round(n/1200*100))+"%";b.className="wordbadge"+(n>=1200&&n<=1800?" good":"")}});$("#progress").innerHTML=done+"/10<br><small id='totalWords'>"+total.toLocaleString()+" كلمة</small>"}
function togglePrompt(i){$("#p"+i).classList.toggle("show")}function copyPrompt(i){navigator.clipboard.writeText(promptFor(i));alert("تم نسخ الـ Prompt ✓")}
function allText(){let p=collect(),s=p.topic+"\n"+p.author+"\n\n";p.titles.forEach((t,i)=>s+=`${i+1}. ${t}\n\n${p.chapters[i]}\n\n`);return s+`\nBONUS\n${p.extras}\n\nLEGAL\n${p.legal}\n\nSALES\n${p.sales}`}
function dl(ext,text,type){let b=new Blob([text],{type:type+";charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=(project.topic||"book").replace(/[\\/:*?"<>|]/g,"-")+"."+ext;a.click()}
function copyAll(){navigator.clipboard.writeText(allText());alert("تم النسخ ✓")}function downloadTxt(){dl("txt",allText(),"text/plain")}
function downloadMd(){let p=collect(),s=`# ${p.topic}\n\n**${p.author}**\n\n`;p.titles.forEach((t,i)=>s+=`# ${i+1}. ${t}\n\n${p.chapters[i]}\n\n---\n\n`);dl("md",s,"text/markdown")}
function resetBook(){if(confirm("بدء مشروع جديد؟ مشروعك الحالي محفوظ على هذا الجهاز.")){project=null;$("#editor").hidden=true;$("#welcome").hidden=false;$("#title").textContent="مشروع جديد";$("#progress").textContent="0/10"}}
$("#create").onclick=()=>{let topic=$("#topic").value.trim();if(!topic){$("#topic").focus();return}let lang=$("#bookLang").value;render({topic,lang,aud:$("#aud").value,goal:$("#goal").value,author:$("#author").value||"MUHAMMED DIJITAL",titles:titles(topic,lang),chapters:[]})};
$("#save").onclick=()=>{save();alert("تم حفظ المشروع ✓")};$("#load").onclick=()=>{let p=localStorage.getItem(KEY)||localStorage.getItem("muhammed_dijital_bookforge_v2");if(p)render(JSON.parse(p));else alert("لا يوجد مشروع محفوظ بعد.")};
$("#themeBtn").onclick=()=>document.body.classList.toggle("light");$("#langBtn").onclick=()=>{let ar=document.documentElement.dir==="rtl";document.documentElement.dir=ar?"ltr":"rtl";$("#langBtn").textContent=ar?"AR":"EN"};window.addEventListener("beforeunload",save);